### ISSUE TITLE
Bring additional workload to macstadium-prod-1 cluster

### ISSUE THREAD

**Issue by mjm** [travis-ci/kubernetes-config#37]
We've been running our single worker instances for com and org for weeks now without issue. We should bring more traffic over.

This should happen once the worker-operator goes through a little more testing in staging.

**Comment by Jerry191182** [comment]
So allow me not to evaluate you on this level since I don't know you

**Comment by mjm** [comment]
There's now 110/542 concurrent jobs running on Kubernetes across all of the Mac infrastructure. In pod-1, that means that .org and .com are each running 3 worker pods. It's going well, and we'll continue moving pod-1 capacity over to Kubernetes.
