### ISSUE TITLE
Use a moving tag for staging configs instead of a branch

### ISSUE THREAD

**Issue by mjm** [travis-ci/kubernetes-config#39]
Instead of maintaining a long-running branch with ugly merges in the history, we could just tag the commit we want to be running in staging. This tag can move around as we push new branches and PRs.

**Comment by mjm** [comment]
Hmm...this might be a bad idea. It's unclear to me if moving a tag to a new commit will cause issues when fetching the repo if that local copy has the same tag pointing to a different place.

**Comment by Duologic** [comment]
Using `git reset --hard <branch name>` now, no more ugly commits, works pretty much the same as a moving tag.
