### ISSUE TITLE
Kubernetes doesn't like worker's graceful shutdown process

### ISSUE THREAD

**Issue by mjm** [travis-ci/kubernetes-config#5]
Our current process for rolling out updates to `worker` on `wjb` has many manual steps and requires a lot of handholding. Applying terraform changes only gets the configuration in place, but then someone has to SSH into the machine and one by one gracefully restart each worker, watching for when the worker has drained its existing pool of jobs and actually restarted. Repeat this in a long loop. It makes worker rollouts very painful when it should be able to be handled automatically.

Kubernetes should be able to solve this problem well: it's what deployments are designed for. However, the way `worker` actually works doesn't seem to match the expectations of Kubernetes. This is mainly an issue for the MacStadium infrastructure, specifically because we have a fixed amount of computing power to offer our jobs. Because of this, we need to manage the rollout and scaling of our worker processes very carefully.

We have configured worker's deployment rollout strategy to have `maxUnavailable: 0` and `maxSurge: 1`. Ideally, what this would mean is that we would always have at most `replicas + 1` worker pods, where one of those pods may be in the process of graceful shutdown. Once it finished shutdown, another pod would be terminated, and another new one brought up to replace it. In this way, we would only ever be exceeding our normal job count by at most one worker's worth of jobs, which we could manage.

This isn't what happens, though. Once Kubernetes tells a worker pod to terminate, it is moved into the "Terminating" state, which means it is no longer ready. Kubernetes doesn't know that the jobs that worker is still running come from a shared pool of resources, so it doesn't think that this pod is relevant to anything it cares about anymore. So it leaves it to finish terminating, but goes on ahead with the rollout as though it were already out of the picture. This can put us in a situation where, in the worst case, we have double the number of worker pods running at once, and half of them are in the process of graceful shutdown. This can cause us to unintentionally end up running far more jobs than we have the computing power to actually run, and could degrade the performance of jobs if we overcommit that much.

I've played with much of the configuration of the deployment to try to find a way to make this work the way we expect, but so far nothing has. The one thing I haven't tried is to add a readiness probe to the worker container. It's possible that this could be used to keep the worker in the ready state until it is done with graceful shutdown, but it's also possible that the Kubernetes will ignore the probe in this situation and still consider the pod to be Terminating.

Some other solutions that we've considered or discussed:

* Increasing the `minReadySeconds` to a large amount (like 30m-1hr) to introduce a fixed pause between when new worker pods are brought up. A downside is that this could maybe leave us at reduced capacity longer than needed, but that would need to be confirmed with testing.
* Using a scheduler extender to be able to represent the amount of compute capacity as an [extended resource](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#extended-resources)
* Using some kind of coordinator to dynamically scale up the pool size of new workers while old pods are shutting down

**Comment by meatballhat** [comment]
I love the idea of reading from a mounted ConfigMap :+1:

**Comment by mjm** [comment]
@meatballhat Cool! Do you have any opinions about the rest of the approach? Like, does tracking currently active jobs in Redis seem reasonable, or is there an obviously better way to collect this information? How easy is it to, from within worker, get the number of processors that are currently running a job.

I've been thinking about this, and worrying about all the different scenarios and whether this data will always be accurate (in cases of crashes or things like that). I guess I can just try to implement it and see how it shakes out and experiment.

**Comment by meatballhat** [comment]
@mjm Tracking total number of processors in redis SGTM, and it's what job-board does when delivering jobs over HTTP, e.g.: https://github.com/travis-ci/job-board/blob/416fb368561302be43718debec0c1c9ce7ce85db/lib/job_board/job_queue.rb#L89-L100

**Comment by mjm** [comment]
We ended up abandoning the approach of using Redis to self-limit in favor of bringing up a custom Kubernetes operator to orchestrate worker rollouts and adjust pool sizes on the fly.

That work is happening in https://github.com/travis-ci/worker-operator

**Comment by mjm** [comment]
Worker-operator is deployed everywhere we have workers in Kubernetes, so I think this is done.
